Implement #50
hpi-swa-teaching/Algernon-Launcher pull request #124
Opened 2020-07-15 09:22 UTC by robertkirsten

Currently we use the help-icon for the three new actions. Maybe @sinnaj-r would be so nice and help us with adding a new icon?
The tests just check whether an action is on top of the resultlist when entering the respective string. Obviously it  is hard to check if the image quitted in a test but maybe somebody has an idea how we can check if the image was saved?

2020-07-15 09:37 UTC, sinnaj-r commented
You can add the following icons as a class method to the IconFactory. You also need to add them to the `initializeFileMapping` and then clear the cache. E.g. by running `ALGIconFactory initializeFileMapping` and then doing the normal cleanup.

```
powerIcon

	^  '(Form
	extent: 22@22
	depth: 32
	fromArray:   #(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1526726656 1526726656 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1744830464 1543503872 0 0 0 4026531840 4026531840 0 0 0 1543503872 1744830464 0 0 0 0 0 0 0 0 67108864 2583691264 4278190080 3674210304 0 0 0 4026531840 4026531840 0 0 0 3674210304 4278190080 2583691264 50331648 0 0 0 0 0 0 2231369728 4278190080 3808428032 822083584 0 0 0 4026531840 4026531840 0 0 0 838860800 3808428032 4278190080 2231369728 0 0 0 0 0 1090519040 4244635648 3992977408 520093696 0 0 0 0 4026531840 4026531840 0 0 0 0 520093696 3992977408 4244635648 1090519040 0 0 0 0 3221225472 4278190080 1409286144 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 1409286144 4278190080 3221225472 0 0 0 671088640 4278190080 3623878656 0 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 0 3623878656 4278190080 671088640 0 0 1828716544 4278190080 2046820352 0 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 0 2046820352 4278190080 1828716544 0 0 2382364672 4278190080 1358954496 0 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 0 1358954496 4278190080 2382364672 0 0 2818572288 4278190080 973078528 0 0 0 0 0 0 4026531840 4026531840 0 0 0 0 0 0 973078528 4278190080 2818572288 0 0 2516582400 4278190080 1660944384 0 0 0 0 0 0 2533359616 2533359616 0 0 0 0 0 0 1660944384 4278190080 2516582400 0 0 1946157056 4278190080 2533359616 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2533359616 4278190080 1946157056 0 0 687865856 4278190080 3573547008 33554432 0 0 0 0 0 0 0 0 0 0 0 0 33554432 3573547008 4278190080 704643072 0 0 0 3221225472 4278190080 1912602624 0 0 0 0 0 0 0 0 0 0 0 0 1912602624 4278190080 3238002688 0 0 0 0 570425344 4093640704 4143972352 654311424 0 0 0 0 0 0 0 0 0 0 654311424 4143972352 4110417920 587202560 0 0 0 0 0 1761607680 4278190080 3825205248 1224736768 0 0 0 0 0 0 0 0 1224736768 3825205248 4278190080 1811939328 0 0 0 0 0 0 16777216 2432696320 4261412864 4278190080 2617245696 822083584 83886080 0 0 83886080 822083584 2617245696 4278190080 4261412864 2466250752 16777216 0 0 0 0 0 0 0 0 1090519040 3741319168 4278190080 4278190080 4160749568 3372220416 3372220416 4160749568 4278190080 4278190080 3774873600 1124073472 0 0 0 0 0 0 0 0 0 0 0 201326592 2113929216 3506438144 4278190080 4278190080 4278190080 4278190080 3523215360 2147483648 234881024 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 150994944 570425344 587202560 150994944 0 0 0 0 0 0 0 0 0)
	offset: 0@0)'
```

```
saveIcon

	^  '(Form
	extent: 22@22
	depth: 32
	fromArray:    #(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 452984832 1073741824 1073741824 1073741824 1073741824 1073741824 1073741824 1073741824 1073741824 1073741824 1073741824 855638016 50331648 0 0 0 0 0 0 0 0 1962934272 4227858432 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 3338665984 285212672 0 0 0 0 0 0 0 3942645760 4177526784 2701131776 3087007744 4278190080 3690987520 2684354560 2684354560 2684354560 2684354560 3288334336 4278190080 4177526784 4278190080 3456106496 285212672 0 0 0 0 0 0 4278190080 3758096384 0 1073741824 4278190080 2684354560 0 0 0 0 1610612736 4278190080 2298478592 3170893824 4278190080 3456106496 285212672 0 0 0 0 0 4278190080 3758096384 0 1073741824 4278190080 2684354560 0 0 0 0 1610612736 4278190080 2147483648 150994944 3170893824 4278190080 3439329280 150994944 0 0 0 0 4278190080 3758096384 0 1073741824 4278190080 3087007744 1073741824 1073741824 1073741824 1073741824 2281701376 4278190080 2147483648 0 150994944 3204448256 4278190080 1711276032 0 0 0 0 4278190080 3758096384 0 973078528 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 2046820352 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 67108864 2248146944 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2499805184 486539264 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 0 0 654311424 1593835520 1224736768 150994944 0 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 0 2181038080 4244635648 4278190080 4278190080 3640655872 637534208 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 1191182336 4278190080 4009754624 2432696320 3238002688 4278190080 3338665984 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 2516582400 4278190080 1694498816 0 50331648 3774873600 4278190080 369098752 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 2516582400 4278190080 1694498816 0 50331648 3774873600 4278190080 369098752 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 1191182336 4278190080 4009754624 2432696320 3238002688 4278190080 3338665984 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 0 2181038080 4244635648 4278190080 4278190080 3640655872 637534208 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 4278190080 3758096384 0 0 0 0 0 654311424 1593835520 1224736768 150994944 0 0 0 0 1610612736 4278190080 2147483648 0 0 0 0 3942645760 4177526784 2701131776 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 2684354560 3405774848 4278190080 1795162112 0 0 0 0 1962934272 4227858432 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 4278190080 3741319168 285212672 0 0 0 0 0 452984832 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 1056964608 939524096 33554432 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
	offset: 0@0)'
```


![Artboard](https://user-images.githubusercontent.com/2962736/87529427-46e11300-c68f-11ea-89f7-ec402b34b7da.png)
![Artboard](https://user-images.githubusercontent.com/2962736/87529430-48124000-c68f-11ea-92ab-4639167dfdd9.png)

2020-07-15 12:14 UTC, BenBals commented
For the tests you could overwrite the commandBlocks and see if they get called.

2020-07-15 12:15 UTC, BenBals requested changes
Looks good iG. Just a few minor things.

Good work!

2020-07-15 12:15 UTC, BenBals commented on packages/Algernon.package/ALGActionVerbFilter.class/class/helpTexts.st
> +		add: 'saverepo'->'saves to Repository with a working copy';
Please update the wiki accordingly.

2020-07-15 12:15 UTC, BenBals commented on packages/Algernon.package/ALGActionVerbFilter.class/class/helpTexts.st
> +		add: 'save'-> 'save the image without closing it';
Please also add these to the wiki

2020-07-15 12:15 UTC, BenBals commented on packages/Algernon.package/ALGQuitType.class/class/algertemList.st
> +as yet unclassified
Please classify.

2020-07-15 12:15 UTC, BenBals commented on packages/Algernon.package/ALGQuitType.class/class/new.commandBlock..st
> +as yet unclassified
Please classify

2020-07-15 12:15 UTC, BenBals commented on packages/Algernon.package/ALGQuitType.class/properties.json
> +	"name" : "ALGQuitType",
Please choose a better name, maybe `ALGSystemCommandType`?

2020-07-15 12:29 UTC, sinnaj-r approved these changes
Looks really good.
I still found a few details, which should be fixed, but then you can merge it imho.

2020-07-15 12:29 UTC, sinnaj-r commented on packages/Algernon.package/ALGQuitType.class/class/algertemList.st
> +	^ {ALGItem withAlgertype: (self new: 'save' commandBlock: [Smalltalk saveSession.]).
Just for comparing the actions in code it would be more readable if you wrote `self snapshot: true andQuit: false`

2020-07-15 12:29 UTC, sinnaj-r commented on packages/AlgernonTests.package/ALGTestActionVerbs.class/instance/testSaveAndQuit.st
> +	self assert: (self items first name = 'saveandquit')
You may want to use `nameOfFirstResult` here (and create something similar for typeName).

2020-07-15 12:29 UTC, sinnaj-r commented on packages/Algernon.package/ALGQuitType.class/class/new.commandBlock..st
> +as yet unclassified
unclassified

2020-07-15 12:29 UTC, sinnaj-r commented on packages/Algernon.package/ALGQuitType.class/class/algertemList.st
> +as yet unclassified
unclassified

2020-07-16 08:27 UTC, BenBals approved these changes
Looks good. Just change the type name and then this should be good to go.

2020-07-16 08:27 UTC, BenBals commented on packages/Algernon.package/ALGSystemCommandType.class/instance/typeName.st
> +	^ 'Quit'
Please update the type name to reflect the class name.

2020-07-17 13:50 UTC, BenBals commented
This should be ready to merge, shouldn't it?

2020-07-17 14:28 UTC, merged