Implement #80v2
hpi-swa-teaching/Algernon-Launcher pull request #155
Opened 2020-08-04 00:19 UTC by phlprcks

finalizes #80 (on a new branch bc the git browser seemingly does not work well with pushing a rebased branch...)

2020-08-04 07:52 UTC, BenBals requested changes
Thank you very much! This looks like a big and noticeable improvement to the code quality! :1st_place_medal: 

I just have two little nitpicks, nothing big.

2020-08-04 07:52 UTC, BenBals commented on packages/Algernon.package/ALGItem.class/instance/nameLessThan.given..st
> +	^(me and: [other not]).
This code is almost the same as `initalsLessThan:given:` please factor out the duplication.

2020-08-04 07:52 UTC, BenBals commented on packages/Algernon.package/ALGItemFilter.class/instance/accepts..st
> +	^ false
This should be `(aString collection size > 1) and: [ self class keywords includes: aStringCollection first ]`

2020-08-04 10:07 UTC, phlprcks commented
@BenBals or @sinnaj-r any ideas why squeak 5.3 on macos-latest has a timeout for testDailyCacheCleanup. That is the only fail - everything else runs smoothly

2020-08-04 10:08 UTC, BenBals commented
This happens all the time and on other branches too. Maybe @sinnaj-r has an idea. It would be cool to see this fixed.

2020-08-04 13:41 UTC, BenBals requested changes

2020-08-04 13:41 UTC, BenBals commented on packages/Algernon.package/ALGItem.class/instance/initialsLessThan.given..st
> +	^(me and: [other not])"
Is there a reason why you left this in as a comment? If not please delete.

2020-08-04 13:41 UTC, BenBals commented on packages/Algernon.package/ALGItem.class/instance/nameLessThan.given..st
> +	"| me other |
Dito.

2020-08-04 14:12 UTC, sinnaj-r commented
> @BenBals or @sinnaj-r any ideas why squeak 5.3 on macos-latest has a timeout for testDailyCacheCleanup. That is the only fail - everything else runs smoothly

I think I've identified the problem: We only increased the timeout for the ALGTest class (+subclasses), but not for the ALGTestInstallation class.
This is not a problem for the other non-ALGTest classes, as they don't execute much logic; however, the testDailyCacheCleanup test does a complete Algernon-Cleanup, which usually takes a long time. 

So simply add following method to the ALGTestInstallation class
```
defaultTimeout

	^ 60 "seconds" 
```

2020-08-04 14:35 UTC, BenBals commented
I did that, see #156

2020-08-04 14:54 UTC, sinnaj-r approved these changes
Apart from the the two remaing comments - see Bens remark - this looks good 👍

2020-08-05 07:54 UTC, phlprcks commented
@BenBals thanks for making me aware of the outcommented parts - that was not on purpose and I oversaw that. Please feel free to merge and close the issue once you can approve :)

2020-08-05 07:57 UTC, BenBals approved these changes
Looks good now.

2020-08-05 07:57 UTC, merged