#140: Coverage improvements
hpi-swa-teaching/Algernon-Launcher pull request #161
Opened 2020-08-05 14:16 UTC by sinnaj-r

2020-08-05 15:01 UTC, sinnaj-r commented
We now have (in the Squeak TestRunner) 100% Coverage 🎉

2020-08-06 08:54 UTC, BenBals requested changes
Looks good, just a few nitpicks.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTest.class/instance/prevAlgernonSingletone..st
> +prevAlgernonSingletone: anObject
I think there is a typo here. It should be `Singleton`

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTest.class/instance/prevAlgernonSingletone..st
> +prevAlgernonSingletone: anObject
Also we have another instance variable starting with `previous` maybe we should be consistent.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestLifecycle.class/instance/testAlgernonChangeShortcut..st
> +	ALGCore setKeyboardBinding: shortcut shallowCopy.
Is here a reason for `shallowCopy` here. `Object>>copy` is defined as `self shallowCopy postCopy`.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestLifecycle.class/instance/testAlgernonSingletoneClose.st
> +testAlgernonSingletoneClose
Same typo.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestLifecycle.class/instance/testAlgernonSingletoneOpen.st
> +testAlgernonSingletoneOpen
Same typo

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testCategoryTypeOpenMethodInBrowser.st
> +	browser :=SystemBrowser default open.
Spacing.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testCategoryTypeOpenMethodInBrowser.st
> +	category:= 'Algernon'.
Spacing.

Maybe just run ohm pretty print?

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testHelpAction.st
> +	self algInstance doActionOnSelectedEvent: nil.
Use `self activateCurrentItemAction`.

2020-08-06 08:54 UTC, BenBals commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testSystemCommandDo.st
> +	called:=false.
Spacing.

2020-08-06 09:19 UTC, BenBals requested changes
Lgtm

2020-08-06 09:19 UTC, BenBals commented on README.md
> -  <img src="https://user-images.githubusercontent.com/44369294/89326002-e93a5800-d689-11ea-89f0-d685e7a4f1e9.png" width="465" alt="Algernon"/>
Please revert this merge.

2020-08-06 09:29 UTC, BenBals approved these changes
Yay! :rocket:

2020-08-06 09:38 UTC, merged