Ignore disabled entries
hpi-swa-teaching/Algernon-Launcher pull request #216
Opened 2021-06-28 11:53 UTC by FranzSw

closes #188

2021-06-29 09:37 UTC, bewee commented
No idea why this happens. Tests are green on my machine. Probably just another CI problem? 😬

2021-06-29 11:38 UTC, FranzSw commented
> No idea why this happens. Tests are green on my machine. Probably just another CI problem? 😬

Did you run it locally with smalltalk CI? Tests in our working images are not really reliable / reproducible

2021-06-29 12:16 UTC, TheGrayStone commented
I think 'Enter Parent Project' is just not disabled in CI mode. Do you know why this menu entry is even there? Maybe we should rewrite the test to manually disable entries and then test that.

2021-06-29 12:20 UTC, bewee commented
> I think 'Enter Parent Project' is just not disabled in CI mode. Do you know why this menu entry is even there? Maybe we should rewrite the test to manually disable entries and then test that.

Sounds good. We could reuse the already existing mock menu entry for that 🎉

2021-06-29 12:22 UTC, TheGrayStone commented
> > I think 'Enter Parent Project' is just not disabled in CI mode. Do you know why this menu entry is even there? Maybe we should rewrite the test to manually disable entries and then test that.
> 
> Sounds good. We could reuse the already existing mock menu entry for that 🎉

Already on it!

2021-06-29 19:16 UTC, TheGrayStone requested changes

2021-06-29 19:16 UTC, TheGrayStone commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testWorldMenuDisabledAreExcluded.st
> +	self deny: (self resultsIncludeName: 'Enter Parent Project')"
```suggestion
```

2021-06-29 19:16 UTC, TheGrayStone commented on packages/Algernon.package/ALGNamedWorldMenuEntry.class/README.md
> +	- xxxxx
```suggestion
```

2021-06-29 19:21 UTC, bewee commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testWorldMenuDisabledAreExcluded.st
> +	self deny: (self resultsIncludeName: 'Enter Parent Project')"
Trailing for now

2021-06-30 08:51 UTC, FranzSw commented on packages/AlgernonTests.package/ALGTestTypes.class/instance/testWorldMenuDisabledAreExcluded.st
> +	menu abandon.
```suggestion
	menu abandon
```

2021-06-30 11:32 UTC, TheGrayStone approved these changes

2021-06-30 11:32 UTC, merged